

namespace CfgSystem
{
	void LoadCfg(bool,bool);
	void SaveCFG(bool,bool);
}

class CGlobalVariables
{
public:
	bool bMenu = false;
	bool triglol = false;
	float Smoothnessyaw;
	float Smoothnesspitch;
	float legitenable;
	float RCSASSIST;
	float AimTeam;
	float AimFOV;
	float AimSpot;
	float Bunnyhop;
	float inattack;
	float radar;
	float velocity;
	float watermark;
	float gloves;
	float knife;
	float knifeskin;
	float triggerkey;
	float skinchanger;
	float skinselection;
	float trigenable;
	float trighead;
	float triggerbody;
	float trigerdelay;
	float speclist;
	float trigteam;
	float autopistol;
	float espbox;
	float healthbar;
	float chams;
	float XQZ;
	float radarsize;
	float radarrange = 40;
	float radarteam;
	float radarnames;
	float radaringame;
	float flRadarPos_x = 120;
	float flRadarPos_y = 120;
	float glovekit1;
	float glovekit2;
	float glovekit3;
	float glovekit4;
	float glovekit5;
	float glovekit6;
	float RCSFOV;
	float RCSSMOOTH;
	float lagcomp;
	float colorsredone = 168;
	float colorsgreenone = 216;
	float colorsblueone = 236;
	float colorsredtwo = 168;
	float colorsgreentwo = 216;
	float colorsbluetwo = 236;
	float colorsredTHREE = 254;
	float colorsgreenTHREE = 254;
	float colorsblueTHREE = 254;
	float colorsredFOUR = 168;
	float colorsgreenFOUR = 216;
	float colorsblueFOUR = 236;
	float colorsredFIVE = 251;
	float colorsgreenFIVE = 219;
	float colorsblueFIVE = 73;
	float ak47skin;
	float awpskin;
	float deagleskin;
	float glockskin;
	float uspskin;
	float m4a1skin;
	float sg553skin;
	float scoutskin;
	float m4a4skin;
	float p2000skin;
	float dualskin;
	float augskin;
	float galilskin;
	float ak47stats;
	float awpstats;
	float deaglestats;
	float glockstats;
	float uspstats;
	float m4a1stats;
	float sg553stats;
	float scoutstats;
	float m4a4stats;
	float p2000stats;
	float dualstats;
	float augstats;
	float galilstats;
	float ak47seed;
	float awpseed;
	float deagleseed;
	float glockseed;
	float uspseed;
	float m4a1seed;
	float sg553seed;
	float scoutseed;
	float m4a4seed;
	float p2000seed;
	float dualseed;
	float augseed;
	float galilseed;
	float esprenderdist;
	float recoilxhair;
	float drawmonitor;
	float f1monitorpos_x = 400;
	float f1monitorpos_y = 400;
	float espweapon;
	float espname;
	float espteam;
	float CHAMTEAM;
	float noflash;
	float nosmoke;
	float slidewalk;
	float mac10skin;
	float mac10stat;
	float mac10seed;
	float p90skin;
	float p90stat;
	float p90seed;
	float m249skin;
	float m249stat;
	float m249seed;
	float g3sg1skin;
	float g3sg1stat;
	float g3sg1seed;
	float famasskin;
	float famasstat;
	float famasseed;
	float fivesevenskin;
	float fivesevenstat;
	float fivesevenseed;
	float umpskin;
	float umpstat;
	float umpseed;
	float xm1000skin;
	float xm1000stat;
	float xm1000seed;
	float bizonskin;
	float bizonstat;
	float bizonseed;
	float mag7skin;
	float mag7stat;
	float mag7seed;
	float negevskin;
	float negevstat;
	float negevseed;
	float sawedskin;
	float sawedstat;
	float sawedseed;
	float tecskin;
	float tecstat;
	float tecseed;
	float mp7skin;
	float mp7stat;
	float mp7seed;
	float mp9skin;
	float mp9stat;
	float mp9seed;
	float novaskin;
	float novastat;
	float novaseed;
	float p250skin;
	float p250stat;
	float p250seed;
	float scarskin;
	float scarstat;
	float scarseed;
	float r8skin;
	float r8stat;
	float r8seed;
	float mp5skin;
	float mp5stat;
	float mp5seed;
	float showrank;
	float nosleeve;
};

inline  CGlobalVariables gCvars;
